In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=["the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "I am a good developer",
      "understand the meaning of words",
      "your videos are good"]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=100000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[60908, 52597, 30820, 82875],
 [60908, 52597, 30820, 60421],
 [60908, 82683, 30820, 45012],
 [55107, 53077, 18086, 74507, 74280],
 [55107, 53077, 18086, 74507, 25061],
 [59201, 60908, 41846, 30820, 43597],
 [21570, 53695, 52593, 74507]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [21]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)
print(embedded_doc)

[[    0     0     0     0 60908 52597 30820 82875]
 [    0     0     0     0 60908 52597 30820 60421]
 [    0     0     0     0 60908 82683 30820 45012]
 [    0     0     0 55107 53077 18086 74507 74280]
 [    0     0     0 55107 53077 18086 74507 25061]
 [    0     0     0 59201 60908 41846 30820 43597]
 [    0     0     0     0 21570 53695 52593 74507]]


In [22]:
## feature representation
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim, input_shape=(sent_length,)))
model.compile("adam","mse")

In [28]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 8, 10)          │     1,000,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,000,000 (3.81 MB)

 Trainable params: 1,000,000 (3.81 MB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 468ms/step


array([[[ 1.53203867e-02,  1.82742998e-03, -2.46199220e-03,
          1.73109658e-02, -2.69615408e-02, -3.71644273e-02,
         -2.92924047e-02,  1.52481236e-02,  1.27634071e-02,
          1.60519145e-02],
        [ 1.53203867e-02,  1.82742998e-03, -2.46199220e-03,
          1.73109658e-02, -2.69615408e-02, -3.71644273e-02,
         -2.92924047e-02,  1.52481236e-02,  1.27634071e-02,
          1.60519145e-02],
        [ 1.53203867e-02,  1.82742998e-03, -2.46199220e-03,
          1.73109658e-02, -2.69615408e-02, -3.71644273e-02,
         -2.92924047e-02,  1.52481236e-02,  1.27634071e-02,
          1.60519145e-02],
        [ 1.53203867e-02,  1.82742998e-03, -2.46199220e-03,
          1.73109658e-02, -2.69615408e-02, -3.71644273e-02,
         -2.92924047e-02,  1.52481236e-02,  1.27634071e-02,
          1.60519145e-02],
        [ 3.16075347e-02,  4.75615524e-02,  3.76173519e-02,
         -4.51156870e-02,  3.54905166e-02,  4.28504981e-02,
          2.64281295e-02,  2.33010203e-03,  8.049346

In [30]:
embedded_doc[0]

array([    0,     0,     0,     0, 60908, 52597, 30820, 82875],
      dtype=int32)

In [39]:
#model.predict(np.expand_dims(embedded_doc[0],axis=0))
model.predict(embedded_doc[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step


array([[[ 1.5320387e-02,  1.8274300e-03, -2.4619922e-03,  1.7310966e-02,
         -2.6961541e-02, -3.7164427e-02, -2.9292405e-02,  1.5248124e-02,
          1.2763407e-02,  1.6051915e-02],
        [ 1.5320387e-02,  1.8274300e-03, -2.4619922e-03,  1.7310966e-02,
         -2.6961541e-02, -3.7164427e-02, -2.9292405e-02,  1.5248124e-02,
          1.2763407e-02,  1.6051915e-02],
        [ 1.5320387e-02,  1.8274300e-03, -2.4619922e-03,  1.7310966e-02,
         -2.6961541e-02, -3.7164427e-02, -2.9292405e-02,  1.5248124e-02,
          1.2763407e-02,  1.6051915e-02],
        [ 1.5320387e-02,  1.8274300e-03, -2.4619922e-03,  1.7310966e-02,
         -2.6961541e-02, -3.7164427e-02, -2.9292405e-02,  1.5248124e-02,
          1.2763407e-02,  1.6051915e-02],
        [ 3.1607535e-02,  4.7561552e-02,  3.7617352e-02, -4.5115687e-02,
          3.5490517e-02,  4.2850498e-02,  2.6428130e-02,  2.3301020e-03,
          8.0493465e-03,  1.4964033e-02],
        [ 2.7039621e-02, -4.4635426e-02,  1.7730284e-02, -4.